/* ============================================================
 *  encyclopedia-data.js  —  single source of truth (parsed)
 * ------------------------------------------------------------
 *  Generated by parsing assets/ai_engineering_encyclopedia.md.
 *  The source .md is authored as a Python build script with
 *  heavily escaped markdown, which is brittle to parse live in
 *  the browser. To keep the static app reliable, the content is
 *  pre-parsed here into a clean, hierarchical structure that the
 *  UI renders dynamically. To regenerate after editing the .md,
 *  see tools/parse_md.py described in the README.
 *
 *  Each concept preserves the 7 canonical fields:
 *    description · library · purpose · relationship
 *    code · good (output) · bad (output) + rca
 *  `viz` selects a generated SVG visual (see visuals.js).
 * ============================================================ */

window.ENCYCLOPEDIA = {
  layers: [
    {
      id: 1,
      title: "Layer 1 · Infrastructure & Data Foundation",
      subtitle: "Inbound Tunnel",
      concepts: [
        {
          id: "1.1", title: "Relational DB (RDBMS)", layer: 1, viz: "db",
          library: "SQLAlchemy · psycopg2 · sqlite3",
          description:
            "A structured database management system storing data in fixed-schema tables linked via explicit relational constraints (foreign keys). Uses ACID properties to guarantee transactional consistency.",
          purpose:
            "Acts as the primary operational source of truth for structured transactional enterprise data.",
          relationship:
            "Feeds raw relational data into Layer 1 data lakes or warehouses via ETL/ELT pipelines before downstream AI embedding ingestion.",
          code:
`import sqlite3
# Establish operational relational DB connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()
cursor.execute("CREATE TABLE users (id INT PRIMARY KEY, name TEXT, tier TEXT)")
cursor.execute("INSERT INTO users VALUES (1, 'Alpha Corp', 'Enterprise')")
conn.commit()
cursor.execute("SELECT * FROM users WHERE tier = 'Enterprise'")
print(cursor.fetchall())`,
          good: "[(1, 'Alpha Corp', 'Enterprise')]\n— structured, schema-validated, indexable row output.",
          bad: '{"id": "missing_id", "tier": ["Enterprise", unknown]}',
          rca: "Loose, schema-breaking structures that crash strict RDBMS ingestion layers.",
        },
        {
          id: "1.2", title: "NoSQL DB", layer: 1, viz: "doc",
          library: "pymongo · redis · cassandra-driver",
          description:
            "Non-relational, schema-less data systems engineered for horizontal scaling, distributed architecture, and highly variable document or graph formats.",
          purpose:
            "Stores semi-structured data such as chat logs, JSON payloads, or dynamic web objects that lack a static schema.",
          relationship:
            "Houses unstructured conversational histories or runtime memory states for Layer 5 LLM orchestrator agents.",
          code:
`# JSON document collection via dict representation
nosql_collection = {}
session_id = "sess_98723"
nosql_collection[session_id] = {
    "user_id": 1,
    "conversation_history": [
        {"role": "user", "text": "Analyze the log files."},
        {"role": "assistant", "text": "Logs initialized."}
    ]
}
print(nosql_collection[session_id])`,
          good: "{'user_id': 1, 'conversation_history': [...]}\n— deeply nested, schema-agnostic, extensible metadata block.",
          bad: "OperationalError: table has no column named conversation_history",
          rca: "Pushing volatile, deeply nested structures into rigid relational rows without flattening first.",
        },
        {
          id: "1.3", title: "Data Warehouse", layer: 1, viz: "warehouse",
          library: "google-cloud-bigquery · snowflake-connector-python · pyodbc",
          description:
            "A highly optimized analytical database for aggregated, historical structured datasets organized into star/snowflake schemas for massive OLAP querying.",
          purpose: "Provides high-throughput historical feature computation and corporate business intelligence.",
          relationship:
            "Consumes cleaned operational entries from Layer 1 systems and supplies historical context / training targets to Layer 3 ML.",
          code:
`def compute_warehouse_metric(mock_table):
    # column-oriented analytical aggregation
    total_spend = sum(row['spend'] for row in mock_table)
    return {"aggregated_spend": total_spend}

rows = [{'id': 1, 'spend': 50000}, {'id': 2, 'spend': 120000}]
print(compute_warehouse_metric(rows))`,
          good: "{'aggregated_spend': 170000}\n— accurate, column-aggregated analytical rollup.",
          bad: "TimeoutError: Query scanned 50TB without partitions or cluster keys.",
          rca: "High-cost, unoptimized, unpartitioned linear table scans.",
        },
        {
          id: "1.4", title: "Data Lake", layer: 1, viz: "lake",
          library: "boto3 (AWS S3) · azure-storage-blob · pyarrow",
          description:
            "A raw repository that ingests massive volumes of unstructured, semi-structured, and structured data in native formats (PDFs, audio, raw logs, CSVs).",
          purpose: "Stores large, heterogeneous datasets cheaply before structural engineering pipelines run.",
          relationship:
            "Raw storage ground. Preprocessing (OCR, chunking, tokenization) taps the lake directly to begin vector generation.",
          code:
`# Raw multi-format file landing inside storage keys
data_lake_s3 = {}
data_lake_s3["raw_contracts/contract_001.pdf"] = b"%PDF-1.4 raw binary"
data_lake_s3["logs/stream.json"] = b"{'event': 'login'}"
print("Ingested:", list(data_lake_s3.keys()))`,
          good: "Ingested: ['raw_contracts/contract_001.pdf', 'logs/stream.json']\n— low-cost, durable landing of raw files.",
          bad: "IncompleteRead: File structure corrupted during transmission.",
          rca: "Unverified, corrupted raw object writes that break downstream parsers.",
        },
        {
          id: "1.5", title: "Data Cleaning & Preprocessing (Tokenization, Chunking, OCR)", layer: 1, viz: "tokens",
          library: "tiktoken · pytesseract · langchain.text_splitter",
          description:
            "Preparing raw text, images, and system data for models: OCR converts images to text, chunking splits documents into coherent segments, tokenization maps text to model indices.",
          purpose: "Standardizes raw data into discrete elements suitable for mathematical embedding systems.",
          relationship: "Consumes raw items from Layer 1 lakes and outputs processed text blocks to Layer 2 embedding models.",
          code:
`import tiktoken
raw_text = "Enterprise data must be chunked and tokenized."
chunks = [raw_text[i:i+25] for i in range(0, len(raw_text), 25)]
encoder = tiktoken.get_encoding("cl100k_base")
tokens = encoder.encode(chunks[0])
print("Chunk:", chunks[0])
print("Tokens:", tokens)`,
          good: "Generated Tokens: [34125, 1102, 452]\n— text converted into integers matching the model vocabulary.",
          bad: "[None, None, 10243, -1]",
          rca: "Out-of-vocabulary mapping / broken encodings from using the wrong tokenizer version.",
        },
        {
          id: "1.6", title: "AI Enrichment (Classification, Extraction, Summarization)", layer: 1, viz: "enrich",
          library: "transformers (Hugging Face) · spacy",
          description:
            "Passing unstructured inputs through linguistic models to generate structured meta-tags, clean summaries, and entity extractions.",
          purpose: "Converts un-indexed paragraphs into high-value metadata dimensions to aid retrieval.",
          relationship: "Enhances chunk structures in Layer 1 before storage in Layer 2 vector databases.",
          code:
`def metadata_extraction(text_chunk):
    entities = [w for w in text_chunk.split() if w.istitle()]
    return {"entities": entities, "summary": text_chunk[:30] + "..."}

chunk = "AcmeCorp integrated PyTorch models inside their orchestration core."
print(metadata_extraction(chunk))`,
          good: "{'entities': ['AcmeCorp', 'PyTorch'], 'summary': 'AcmeCorp integrated PyTorch mo...'}\n— clean structural metadata enrichment.",
          bad: "{'entities': [], 'summary': ''}",
          rca: "Silent failures: entities missed due to case-formatting errors, producing empty attributes.",
        },
        {
          id: "1.7", title: "Feature Engineering", layer: 1, viz: "scaler",
          library: "scikit-learn · pandas · numpy",
          description: "Transforming raw metrics into informative variables (features) that help ML algorithms recognize patterns.",
          purpose: "Maximizes prediction accuracy by explicitly revealing patterns to the model.",
          relationship: "Prepares tabular datasets out of warehouses for classical Layer 3 supervised modeling.",
          code:
`from sklearn.preprocessing import StandardScaler
import numpy as np
raw = np.array([[10.0], [100.0], [1000.0]])
scaler = StandardScaler()
print(scaler.fit_transform(raw))`,
          good: "[[-1.22], [0.0], [1.22]]\n— zero-centered, unit-variance features that prevent gradient instability.",
          bad: "[[NaN], [NaN], [NaN]]",
          rca: "Standard-deviation division errors from feeding zero-variance inputs into scaling pipelines.",
        },
        {
          id: "1.8", title: "Outliers", layer: 1, viz: "outliers",
          library: "scikit-learn (IsolationForest) · scipy",
          description: "Data points that differ significantly from the rest of the set; they can corrupt training metrics and distort distributions.",
          purpose: "Anomaly detection, data cleaning, and dataset hygiene optimization.",
          relationship: "Runs as an early sanitation layer in Layer 1 feature pipelines before values reach Layer 3 predictors.",
          code:
`from sklearn.ensemble import IsolationForest
import numpy as np
data = np.array([[1.0], [1.1], [0.9], [105.2]])  # 105.2 is extreme
clf = IsolationForest(contamination=0.25, random_state=42)
print("Classes:", clf.fit_predict(data))  # 1 = normal, -1 = outlier`,
          good: "Outlier classifications: [ 1  1  1 -1]\n— successfully flags the anomaly (105.2 → -1).",
          bad: "Outlier classifications: [1 1 1 1]",
          rca: "Severe anomalies missed because the contamination parameter is misconfigured.",
        },
      ],
    },

    {
      id: 2,
      title: "Layer 2 · Vector Ecosystem & Knowledge Retrieval",
      subtitle: "Knowledge Injection",
      concepts: [
        {
          id: "2.1", title: "Vector Embeddings & Dimensions", layer: 2, viz: "cosine",
          library: "sentence-transformers · openai-python",
          description: "Mapping linguistic constructs into real-valued, multi-dimensional coordinate spaces. The count of axes is the vector's dimensionality.",
          purpose: "Encodes semantic patterns into vectors where distance reflects meaning.",
          relationship: "Consumes chunks from Layer 1 prep and stores resulting vectors in Layer 2 vector-DB indices.",
          code:
`import numpy as np
v_db   = np.array([0.98, 0.01, 0.05])
v_arch = np.array([0.92, 0.03, 0.09])
v_cake = np.array([0.02, 0.95, 0.12])
def sim(a, b): return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print(f"Tech Sim:  {sim(v_db, v_arch):.4f}")
print(f"Cross Sim: {sim(v_db, v_cake):.4f}")`,
          good: "Tech Sim: 0.9992 · Cross Sim: 0.0381\n— true mathematical semantic distinction.",
          bad: "Tech Sim: 0.0000 · Cross Sim: 0.0000",
          rca: "Orthogonal collapse from dimension-length mismatches or uninitialized weights.",
        },
        {
          id: "2.2", title: "Embedding Models", layer: 2, viz: "embed",
          library: "sentence-transformers (all-MiniLM-L6-v2, bge-large-en-v1.5)",
          description: "Pre-trained deep networks that convert raw tokens into stable, high-fidelity dense vectors.",
          purpose: "Generates semantic vector spaces for text fragments.",
          relationship: "Core engine producing values for Layer 2 vector DBs and real-time user-query vectors.",
          code:
`from sentence_transformers import SentenceTransformer
engine = SentenceTransformer('all-MiniLM-L6-v2')
vector = engine.encode(["Connect data pipeline to vector repository."])
print(f"Dims: {len(vector[0])} | Sample: {vector[0][:3]}")`,
          good: "Vector Dimensions: 384 | Sample: [-0.043, 0.021, 0.084]\n— valid low-variance dense representation.",
          bad: "Vector Dimensions: 1 | Sample: [NaN]",
          rca: "Internal tensor errors or empty inputs crashing the neural mapping layer.",
        },
        {
          id: "2.3", title: "Vector Database & Indexing (HNSW, IVF)", layer: 2, viz: "ann",
          library: "faiss · chromadb · pinecone-client",
          description: "A storage engine for vectors optimized for fast spatial retrieval via Approximate Nearest Neighbor indices. IVF clusters to limit search space; HNSW builds a multi-layer graph for logarithmic routing.",
          purpose: "Sub-millisecond similarity search over millions of high-dimensional vectors.",
          relationship: "Primary search engine for Layer 2 / Layer 5 RAG pipelines.",
          code:
`import faiss, numpy as np
dims, n = 4, 1000
np.random.seed(42)
vectors = np.random.random((n, dims)).astype('float32')
index = faiss.IndexHNSWFlat(dims, 16)  # 16 links per node layer
index.add(vectors)
query = np.random.random((1, dims)).astype('float32')
d, i = index.search(query, k=2)
print("Match Indices:", i)
print("L2 Distances:", d)`,
          good: "Nearest Match Indices: [[743 109]]\n— logarithmic extraction of closest match IDs.",
          bad: "[[ -1 -1 ]]",
          rca: "Memory-allocation faults / empty index space returning uninitialized negative flags.",
        },
        {
          id: "2.4", title: "Retrieval-Augmented Generation (RAG): Offline vs Online", layer: 2, viz: "ragflow",
          library: "langchain · llama-index",
          description: "Pulls relevant external facts into a model's prompt context. Offline: read → clean & chunk → embed → populate vector DB. Online: embed query → search → inject chunks into prompt → call LLM.",
          purpose: "Eliminates hallucinations by providing real-time, verified factual context.",
          relationship: "Orchestrates Layer 1 prep, Layer 2 vector search, and Layer 4 LLM generation.",
          code:
`def execute_online_rag(user_query, index):
    context = index.get(user_query, "Fallback Default Context")
    prompt = (f"Context: {context}\\n"
              f"Question: {user_query}\\n"
              f"Answer using only the context:")
    return prompt

store = {"get system metrics": "CPU load is 42%."}
print(execute_online_rag("get system metrics", store))`,
          good: "Context: CPU load is 42%... Answer using only...\n— structured prompt with accurate context.",
          bad: "Context: None  Question: get system metrics...",
          rca: "Missing context because query and document embeddings don't match.",
        },
        {
          id: "2.5", title: "CAG (Context-Augmented Generation) & Cache", layer: 2, viz: "cache",
          library: "vllm · redis",
          description: "Pre-loads entire reference texts into long-context windows ahead of time instead of querying a vector DB on the fly, relying on cache layers near the compute engine.",
          purpose: "Bypasses retrieval to provide deep, global context for long documents.",
          relationship: "Replaces traditional Layer 2 RAG when the context fits within modern model windows.",
          code:
`system_cache = {}
GLOBAL_DOC = "Manual V2.4: Port 443 restricted. Port 8080 allows dev."
def deploy_cag(user_prompt):
    ctx = system_cache.get("global_doc", GLOBAL_DOC)
    return f"Context: {ctx} | Request: {user_prompt}"

system_cache["global_doc"] = GLOBAL_DOC
print(deploy_cag("Can I access dev?"))`,
          good: "Context: Manual V2.4... | Request: Can I access dev?\n— immediate generation from fully cached context.",
          bad: "CacheMissError: Context not found in memory.",
          rca: "Large context files continually drop out of cache, forcing slow re-indexing cycles.",
        },
        {
          id: "2.6", title: "KV Cache", layer: 2, viz: "kvcache",
          library: "vllm · transformers (inference engines)",
          description: "Saves Key-Value attention tensors for past tokens during generation, avoiding recomputation for every new token.",
          purpose: "Speeds up text generation and significantly reduces inference latency.",
          relationship: "Vital in-memory acceleration layer inside Layer 4 LLM inference loops.",
          code:
`class MockKVCache:
    def __init__(self): self.cache = []
    def step(self, token_tensor):
        self.cache.append(token_tensor)
        # O(N^2) -> O(1) per generation step
        return "Inference Time Step Complexity: O(1)"

kv = MockKVCache()
print(kv.step([0.25, -0.12]))`,
          good: "Inference Time Step Complexity: O(1)\n— constant-time processing during generation loops.",
          bad: "Out-of-Memory (OOM): Tensor allocation failed at sequence length 8192.",
          rca: "Long context sessions fill limited GPU VRAM with massive KV-cache data.",
        },
      ],
    },

    {
      id: 3,
      title: "Layer 3 · Core Algorithmic Frameworks",
      subtitle: "Traditional → Deep Learning",
      concepts: [
        {
          id: "3.1", title: "Supervised Learning & Classification", layer: 3, viz: "classify",
          library: "scikit-learn",
          description: "Models learn a mapping from labeled inputs (X → y). Classifiers group categorical outputs: logistic regression (probability boundaries), k-NN (nearest-neighbor votes), decision trees, random forests (tree ensembles), SVM (margin maximization).",
          purpose: "Automated categorization, risk scoring, and intent classification.",
          relationship: "Provides a fast, cost-effective inference alternative alongside massive Layer 4 deep models.",
          code:
`from sklearn.ensemble import RandomForestClassifier
import numpy as np
X = np.array([[0.1, 0.2], [0.9, 0.8], [0.15, 0.22], [0.88, 0.79]])
y = np.array([0, 1, 0, 1])
clf = RandomForestClassifier(n_estimators=10, random_state=42)
clf.fit(X, y)
print("Intent Class:", clf.predict([[0.12, 0.18]]))`,
          good: "Inference Intent Class: [0]\n— high-precision categorical prediction.",
          bad: "ValueError: Input contains NaN or infinity.",
          rca: "Uncleaned null features pass into the training loop, crashing the estimator.",
        },
        {
          id: "3.2", title: "Unsupervised Learning & Clustering", layer: 3, viz: "cluster",
          library: "scikit-learn (KMeans, DBSCAN)",
          description: "Algorithms that find hidden groupings without pre-existing labels, grouping points by distance metrics.",
          purpose: "Audience profiling, data discovery, and automated log analysis.",
          relationship: "Groups related documents or system logs during early Layer 1 preprocessing.",
          code:
`from sklearn.cluster import KMeans
import numpy as np
features = np.array([[1.2, 1.0], [1.0, 1.3], [50.1, 48.2], [49.8, 51.1]])
engine = KMeans(n_clusters=2, random_state=42, n_init='auto')
engine.fit(features)
print("Clusters:", engine.labels_)`,
          good: "Assigned cluster identities: [0 0 1 1]\n— distinct groupings across distance space.",
          bad: "Assigned cluster identities: [0 0 0 0]",
          rca: "Model collapse: bad scaling compresses all items into a single cluster.",
        },
        {
          id: "3.3", title: "PCA & Non-Linearity", layer: 3, viz: "pca",
          library: "scikit-learn (PCA, KernelPCA)",
          description: "PCA projects high-dimensional features onto lower-dimensional axes while preserving variance. Non-linearity describes patterns that straight lines can't map, needing kernels or activation functions.",
          purpose: "Feature-size reduction, data compression, and noise removal.",
          relationship: "Compresses high-dimensional data before Layer 3 classifiers or visualizers.",
          code:
`from sklearn.decomposition import PCA
import numpy as np
high_dim = np.random.rand(10, 50)
pca = PCA(n_components=2)
reduced = pca.fit_transform(high_dim)
print("Reduced shape:", reduced.shape)`,
          good: "Reduced Matrix shape: (10, 2)\n— features simplified into a clean 2-D matrix.",
          bad: "ValueError: n_components must be <= min(n_samples, n_features)",
          rca: "Dimension target set too high for the number of sample records.",
        },
        {
          id: "3.4", title: "Time Series", layer: 3, viz: "timeseries",
          library: "statsmodels (ARIMA) · prophet",
          description: "Sequential data points at constant intervals. Points are correlated over time, breaking the independence assumptions of standard ML.",
          purpose: "Capacity scaling, server-load modeling, and financial trend projection.",
          relationship: "Drives scheduling logic and resource forecasts inside Layer 5 orchestration.",
          code:
`from statsmodels.tsa.arima.model import ARIMA
import numpy as np
traffic = np.array([102, 105, 110, 118, 125, 131, 140], dtype=float)
model = ARIMA(traffic, order=(1, 1, 0)).fit()
print("Forecast:", model.forecast(steps=1))`,
          good: "Next steps forecast: [147.23]\n— accurate, trend-aware sequence forecast.",
          bad: "ConvergenceWarning: Maximum Likelihood optimization failed to converge.",
          rca: "Highly erratic sequence changes cause parameter optimization to fail.",
        },
        {
          id: "3.5", title: "Neural Networks (ANN, RNN, CNN, LSTM, BLSTM)", layer: 3, viz: "nn",
          library: "torch (PyTorch) · torch.nn",
          description: "Deep-learning building blocks. ANN: layers of connected nodes. RNN: passes memory across steps. LSTM/BLSTM: gating to retain long-range context. CNN: sliding filters for spatial patterns (images).",
          purpose: "Core engines for language parsing, sequence modeling, and computer vision.",
          relationship: "Structural predecessors to Layer 4 parallelized self-attention Transformer blocks.",
          code:
`import torch
import torch.nn as nn
lstm = nn.LSTM(input_size=10, hidden_size=20, batch_first=True)
seq = torch.randn(1, 5, 10)  # batch=1, len=5, features=10
out, (hn, cn) = lstm(seq)
print("LSTM output shape:", out.shape)`,
          good: "LSTM Sequence Output shape: torch.Size([1, 5, 20])\n— consistent temporal transformation across hidden states.",
          bad: "RuntimeError: input must have 3 dimensions",
          rca: "Matrix fragments with missing dimension shapes break the tensor architecture.",
        },
        {
          id: "3.6", title: "Weights & Hyperparameters", layer: 3, viz: "weights",
          library: "torch.optim · scikit-learn",
          description: "Weights are values the model learns. Hyperparameters are engineer-set knobs: learning rate (step size), epochs (full passes), batch size, max depth (tree limits), regularization (overfit penalties).",
          purpose: "Tunes and optimizes model convergence behavior.",
          relationship: "Controls whether Layer 3 / Layer 4 models generalize or fail to under/over-fit.",
          code:
`import torch
w = torch.tensor([0.5], requires_grad=True)
learning_rate = 0.01
loss = w * 2
loss.backward()
with torch.no_grad():
    w -= learning_rate * w.grad
print("Updated Weight:", w.item())`,
          good: "Updated Weight Parameter Value: 0.48\n— smooth gradient-step minimization.",
          bad: "Updated Weight Parameter Value: -12450.12",
          rca: "Exploding gradients from an excessively high learning rate overshoot violently.",
        },
        {
          id: "3.7", title: "Cost Function, Gradient Descent & Backpropagation", layer: 3, viz: "gradient",
          library: "torch.optim · torch.nn.MSELoss",
          description: "Cost function measures prediction error. Backpropagation computes each weight's contribution to that error via the chain rule. Gradient descent updates weights to minimize error.",
          purpose: "The mathematical engine that lets neural networks learn from mistakes.",
          relationship: "Drives training updates for Layer 3 deep models and Layer 4 foundation architectures.",
          code:
`import torch
import torch.nn as nn
pred = torch.tensor([2.5], requires_grad=True)
target = torch.tensor([3.0])
loss = nn.MSELoss()(pred, target)
loss.backward()
print("Gradient via Backprop:", pred.grad.item())`,
          good: "Calculated Gradient Value: -1.0\n— clear feedback vector pointing toward error minimization.",
          bad: "Calculated Gradient Value: 0.0",
          rca: "Vanishing gradients from bad activation configs render the network unable to learn.",
        },
        {
          id: "3.8", title: "Activation Functions (ReLU, GeLU, Softmax, …)", layer: 3, viz: "activation",
          library: "torch.nn.functional",
          description: "Equations inserted into layers to introduce non-linearity. ReLU/LeakyReLU clip internal layers; Sigmoid/Softmax produce probabilities; GeLU/SiLU give smooth non-linearities in modern Transformers.",
          purpose: "Introduces non-linear learning capacity across stacked layers.",
          relationship: "Implemented inside hidden layers of Layer 3 deep models and Layer 4 Transformers.",
          code:
`import torch
import torch.nn.functional as F
x = torch.tensor([-2.0, 0.0, 4.0])
print("ReLU:", F.relu(x))
print("GeLU:", F.gelu(x))`,
          good: "ReLU values: tensor([0., 0., 4.])\n— negative activation signals zeroed out.",
          bad: "tensor([-2., 0., 4.])",
          rca: "Linear identity pass-through from uninstantiated activation classes — no non-linear learning.",
        },
      ],
    },

    {
      id: 4,
      title: "Layer 4 · Advanced Architectures & Generative AI",
      subtitle: "The Cognitive Layer",
      concepts: [
        {
          id: "4.1", title: "Attention Mechanisms (QKV, Multi-Head, Positional)", layer: 4, viz: "attention",
          library: "torch.nn.MultiheadAttention · transformers",
          description: "Self-attention assesses relationships between all tokens simultaneously by projecting them into Queries, Keys, and Values to compute attention weights. Multi-head runs this in parallel; positional encoders inject sequence order.",
          purpose: "Processes rich, long-range semantic relationships across text in parallel.",
          relationship: "The core block powering Layer 4 Transformers, LLMs, and reasoning models.",
          code:
`import torch
import torch.nn as nn
mha = nn.MultiheadAttention(embed_dim=8, num_heads=2)
q = torch.randn(3, 1, 8); k = torch.randn(3, 1, 8); v = torch.randn(3, 1, 8)
out, weights = mha(q, k, v)
print("Output shape:", out.shape)
print("Weights shape:", weights.shape)`,
          good: "Contextualized output shape: torch.Size([3, 1, 8])\n— tokens processed with context shared across heads.",
          bad: "RuntimeError: Misaligned head dimension configurations",
          rca: "Embedding dim not divisible by head count crashes the tensor path.",
        },
        {
          id: "4.2", title: "Transformers & NLP", layer: 4, viz: "transformer",
          library: "transformers (Hugging Face)",
          description: "An architecture that replaced recurrent loops with parallelized multi-head self-attention, revolutionizing NLP.",
          purpose: "Massive-scale language modeling, translation, and parallelized text processing.",
          relationship: "Foundation for all large generative models in Layer 4 and Layer 5 pipelines.",
          code:
`from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
print("Tokenizer:", type(tokenizer))`,
          good: "<class 'transformers...GPT2TokenizerFast'>\n— properly loaded text-parsing engine.",
          bad: "OSError: Model name identifier not recognized across repositories.",
          rca: "Broken links or typos in model strings halt execution.",
        },
        {
          id: "4.3", title: "LLMs & Mixture of Experts (MoE)", layer: 4, viz: "moe",
          library: "transformers · vllm · deepspeed",
          description: "Massive models trained on huge corpora. MoE splits layers into specialized sub-networks ('experts'); a router sends each token to the best-suited experts, keeping inference compute low.",
          purpose: "High-capacity general intelligence, conversational logic, and code generation.",
          relationship: "Central cognitive engine for Layer 5 orchestration and business automation.",
          code:
`def moe_router(token_input):
    score = sum(token_input)
    if score > 0.5:
        return "Route to Expert Node 1 [Coding Specialist]"
    return "Route to Expert Node 2 [Creative Specialist]"

print(moe_router([0.1, 0.2, 0.4]))`,
          good: "Route to Expert Node 1 [Coding Specialist]\n— dynamic compute savings via targeted routing.",
          bad: "Router Error: Overloading Expert 1 while Expert 2 stays unutilized.",
          rca: "Routing bottlenecks slow generation and waste architecture capacity.",
        },
        {
          id: "4.4", title: "Large Reasoning Models", layer: 4, viz: "reasoning",
          library: "custom HF configs · commercial inference runtimes",
          description: "Models engineered to generate extended hidden chains of thought (reasoning tokens) before answering, solving complex logic, math, and coding problems.",
          purpose: "Advanced algorithmic optimization, deep engineering, and logic verification.",
          relationship: "Replaces standard LLM layers when tasks need planning over immediate generation.",
          code:
`def execute_reasoning_model(query):
    steps = ["Verify constraint A", "Analyze variable B", "Refine output matrix"]
    return {"reasoning_steps": steps, "output": "Validated Resolution"}

print(execute_reasoning_model("Optimize the scaling rules."))`,
          good: "{'reasoning_steps': ['Verify constraint A', ...], 'output': 'Validated...'}\n— verifiable step-by-step reasoning ensures consistency.",
          bad: "{'reasoning_steps': [], 'output': 'Hallucinated Guess'}",
          rca: "Skipping planning steps leads to wrong assumptions or instant hallucination.",
        },
        {
          id: "4.5", title: "Fine-Tuning", layer: 4, viz: "finetune",
          library: "peft (LoRA) · transformers (Trainer API)",
          description: "Training a pre-trained base model further on a smaller, high-quality labeled dataset to adapt it to a specific domain or task — connecting general models to supervised learning.",
          purpose: "Tailoring tone, adapting to corporate nomenclature, and enforcing output schemas.",
          relationship: "Takes large Layer 4 base models and updates weights for targeted applications.",
          code:
`from peft import LoraConfig
import torch.nn as nn
base_layer = nn.Linear(10, 10)
cfg = LoraConfig(r=8, lora_alpha=16, target_modules=None, lora_dropout=0.05)
print("LoRA rank:", cfg.r)`,
          good: "LoRA Fine-Tuning rank: 8\n— efficient parameter updates via lightweight adapters.",
          bad: "RuntimeError: Weight matrix mismatch during parameter adaptation.",
          rca: "Adapters don't align with base-model layers, corrupting training matrices.",
        },
      ],
    },

    {
      id: 5,
      title: "Layer 5 · Orchestration, Production & LLMOps",
      subtitle: "The Application Layer",
      concepts: [
        {
          id: "5.1", title: "LangGraph & Orchestration (Think › Execute › Review)", layer: 5, viz: "agentloop",
          library: "langgraph · langchain",
          description: "Build stateful, multi-agent systems with cyclic graph workflows, looping through Think → Execute → Review to solve multi-stage tasks autonomously.",
          purpose: "Autonomous task execution, resilient error correction, reliable multi-agent systems.",
          relationship: "The master layer tying together Layer 1 inputs, Layer 2 search, and Layer 4 generation.",
          code:
`class ProductionAgentState:
    def __init__(self): self.node = "Think"
    def advance(self, result):
        if self.node == "Think": self.node = "Execute"
        elif self.node == "Execute": self.node = "Review"
        elif self.node == "Review" and result == "Valid": self.node = "Complete"

agent = ProductionAgentState()
agent.advance("Executed actions")
print("Loop position:", agent.node)`,
          good: "Agent Lifecycle position: Execute\n— controlled, deterministic state transitions.",
          bad: "InfiniteLoopException: Agent cycling between Think and Execute.",
          rca: "Poor termination logic creates infinite loops that run up massive API bills.",
        },
        {
          id: "5.2", title: "Latency & Production", layer: 5, viz: "latency",
          library: "vllm · triton-inference-server",
          description: "Optimizing model serving to minimize response time — balancing Time-To-First-Token (TTFT) and inter-token latency — while handling concurrent requests live.",
          purpose: "Scalable, responsive user-facing AI service delivery.",
          relationship: "Optimizes Layer 4 inference to meet performance SLAs for Layer 5 applications.",
          code:
`import time
def record_telemetry():
    start = time.time()
    time.sleep(0.042)  # optimized vLLM response
    return {"TTFT_ms": (time.time() - start) * 1000}

print(record_telemetry())`,
          good: "{'TTFT_ms': 42.12}\n— high-speed, responsive inference performance.",
          bad: "{'TTFT_ms': 18500.0}",
          rca: "Unoptimized batch-serving queues create unacceptable user delay.",
        },
        {
          id: "5.3", title: "Evals & Model Evaluation (A/B, Ragas)", layer: 5, viz: "evals",
          library: "ragas · langsmith · mlflow",
          description: "Quantifying output quality with rigorous metrics: faithfulness and answer relevance benchmarks, plus production A/B testing across model variants.",
          purpose: "Quality control guardrails, regression monitoring, reliable optimization choices.",
          relationship: "Evaluates end-to-end Layer 1–4 components before production deployment.",
          code:
`def faithfulness(answer, context):
    matches = [w for w in answer.split() if w in context]
    score = len(matches) / max(len(answer.split()), 1)
    return {"faithfulness_score": score}

print(faithfulness("CPU load 42 percent",
                   "System confirms CPU load 42 percent."))`,
          good: "{'faithfulness_score': 0.75}\n— accurate evaluation of model grounding.",
          bad: "AssertionError: baseline ground-truth values are missing.",
          rca: "Cannot evaluate performance because baseline test sets are undefined.",
        },
        {
          id: "5.4", title: "AI Stack Infrastructure (On-Prem · Cloud · Local GPUs)", layer: 5, viz: "infra",
          library: "nvidia-smi · CUDA drivers · torch.cuda",
          description: "The compute layer powering all AI systems: on-prem hardware (max security), cloud clusters (rapid auto-scaling), or local boxes (zero-cost prototyping).",
          purpose: "Raw physical acceleration for high-dimensional matrix mathematics.",
          relationship: "The foundation powering every layer of the data tunnel and training ecosystem.",
          code:
`import torch
available = torch.cuda.is_available()
device = torch.cuda.get_device_name(0) if available else "CPU only"
print(f"GPU Acceleration: {available}")
print(f"Infrastructure: {device}")`,
          good: "GPU Acceleration: True · Infrastructure: NVIDIA H100\n— valid high-performance compute environment.",
          bad: "GPU Acceleration State Active: False",
          rca: "Falls back to slow CPU execution from broken CUDA configs or missing drivers.",
        },
      ],
    },
  ],
};

/* convenience lookups */
window.ENC_BY_LAYER = {};
window.ENC_BY_ID = {};
window.ENCYCLOPEDIA.layers.forEach((layer) => {
  window.ENC_BY_LAYER[layer.id] = layer;
  layer.concepts.forEach((c) => { window.ENC_BY_ID[c.id] = c; });
});
